; ModuleID = '/project/test/llvm-test-suite/MultiSource/Applications/SPASS/doc-proof.c'
source_filename = "/project/test/llvm-test-suite/MultiSource/Applications/SPASS/doc-proof.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct._IO_FILE = type { i32, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, %struct._IO_marker*, %struct._IO_FILE*, i32, i32, i64, i16, i8, [1 x i8], i8*, i64, %struct._IO_codecvt*, %struct._IO_wide_data*, %struct._IO_FILE*, i8*, i64, i32, [20 x i8] }
%struct._IO_marker = type opaque
%struct._IO_codecvt = type opaque
%struct._IO_wide_data = type opaque
%struct.MEMORY_BIGBLOCKHEADERHELP = type { %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP* }
%struct.MEMORY_RESOURCEHELP = type { i8*, i8*, i8*, i8*, i32, i32, i32 }
%struct.PROOFSEARCH_HELP = type { %struct.LIST_HELP*, %struct.LIST_HELP*, %struct.LIST_HELP*, %struct.LIST_HELP*, %struct.SHARED_INDEX_NODE*, %struct.LIST_HELP*, %struct.SHARED_INDEX_NODE*, %struct.LIST_HELP*, %struct.SORTTHEORY_HELP*, %struct.SORTTHEORY_HELP*, %struct.SORTTHEORY_HELP*, %struct.SHARED_INDEX_NODE*, %struct.LIST_HELP*, i32*, i32*, %struct.LIST_HELP*, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.SORTTHEORY_HELP = type { %struct.st*, [4000 x %struct.NODE_HELP*], %struct.LIST_HELP*, %struct.LIST_HELP*, i32 }
%struct.st = type { %struct.subst*, %struct.LIST_HELP*, %struct.LIST_HELP*, i16, i16 }
%struct.subst = type { %struct.subst*, i32, %struct.term* }
%struct.term = type { i32, %union.anon, %struct.LIST_HELP*, i32, i32 }
%union.anon = type { %struct.LIST_HELP* }
%struct.NODE_HELP = type { %struct.LIST_HELP*, i32, i32, i32, %struct.LIST_HELP*, i32 }
%struct.SHARED_INDEX_NODE = type { %struct.st*, [3001 x %struct.term*], [4000 x %struct.term*], i32 }
%struct.LIST_HELP = type { %struct.LIST_HELP*, i8* }
%struct.CLAUSE_HELP = type { i32, i32, i32, i32, i64*, i32, %struct.LIST_HELP*, %struct.LIST_HELP*, i32, i32, %struct.LITERAL_HELP**, i32, i32, i32, i32 }
%struct.LITERAL_HELP = type { i32, i32, i32, %struct.CLAUSE_HELP*, %struct.term* }

@dp_DEPTH = dso_local global i32 0, align 4
@.str = private unnamed_addr constant [59 x i8] c"\0ANOTE: clauses with following numbers have not been found:\00", align 1
@.str.1 = private unnamed_addr constant [4 x i8] c"%d \00", align 1
@.str.2 = private unnamed_addr constant [70 x i8] c"NOTE: Following clauses in reduced proof have incomplete parent sets:\00", align 1
@.str.3 = private unnamed_addr constant [46 x i8] c"\0A\0AHere is a proof with depth %d, length %d :\0A\00", align 1
@stdout = external dso_local global %struct._IO_FILE*, align 8
@memory_OFFSET = external dso_local global i32, align 4
@memory_BIGBLOCKS = external dso_local global %struct.MEMORY_BIGBLOCKHEADERHELP*, align 8
@memory_MARKSIZE = external dso_local global i32, align 4
@memory_FREEDBYTES = external dso_local global i64, align 8
@memory_MAXMEM = external dso_local global i64, align 8
@memory_ARRAY = external dso_local global [0 x %struct.MEMORY_RESOURCEHELP*], align 8
@memory_ALIGN = external dso_local constant i32, align 4
@.str.4 = private unnamed_addr constant [7 x i8] c"%s.prf\00", align 1
@.str.5 = private unnamed_addr constant [2 x i8] c"w\00", align 1
@.str.6 = private unnamed_addr constant [26 x i8] c"begin_problem(Unknown).\0A\0A\00", align 1
@.str.7 = private unnamed_addr constant [23 x i8] c"list_of_descriptions.\0A\00", align 1
@.str.8 = private unnamed_addr constant [8 x i8] c"name({*\00", align 1
@.str.9 = private unnamed_addr constant [6 x i8] c"*}).\0A\00", align 1
@.str.10 = private unnamed_addr constant [16 x i8] c"author({*SPASS \00", align 1
@.str.11 = private unnamed_addr constant [6 x i8] c"V 2.1\00", align 1
@.str.12 = private unnamed_addr constant [24 x i8] c"status(unsatisfiable).\0A\00", align 1
@.str.13 = private unnamed_addr constant [63 x i8] c"description({*File generated by SPASS containing a proof.*}).\0A\00", align 1
@.str.14 = private unnamed_addr constant [15 x i8] c"end_of_list.\0A\0A\00", align 1
@.str.15 = private unnamed_addr constant [18 x i8] c"list_of_symbols.\0A\00", align 1
@.str.16 = private unnamed_addr constant [24 x i8] c"\0Alist_of_proof(SPASS).\0A\00", align 1
@.str.17 = private unnamed_addr constant [15 x i8] c"end_problem.\0A\0A\00", align 1
@.str.18 = private unnamed_addr constant [24 x i8] c"\0ADFG Proof printed to: \00", align 1

; Function Attrs: noinline nounwind uwtable
define dso_local void @dp_Init() #0 {
  store i32 0, i32* @dp_DEPTH, align 4
  ret void
}

; Function Attrs: noinline nounwind uwtable
define dso_local %struct.LIST_HELP* @dp_PrintProof(%struct.PROOFSEARCH_HELP* noundef %0, %struct.LIST_HELP* noundef %1, i8* noundef %2) #0 {
  %4 = alloca %struct.PROOFSEARCH_HELP*, align 8
  %5 = alloca %struct.LIST_HELP*, align 8
  %6 = alloca i8*, align 8
  %7 = alloca %struct.LIST_HELP*, align 8
  %8 = alloca %struct.LIST_HELP*, align 8
  %9 = alloca %struct.LIST_HELP*, align 8
  %10 = alloca %struct.LIST_HELP*, align 8
  %11 = alloca %struct.LIST_HELP*, align 8
  %12 = alloca %struct.LIST_HELP*, align 8
  %13 = alloca %struct.LIST_HELP*, align 8
  %14 = alloca %struct.LIST_HELP*, align 8
  %15 = alloca i32*, align 8
  store %struct.PROOFSEARCH_HELP* %0, %struct.PROOFSEARCH_HELP** %4, align 8
  store %struct.LIST_HELP* %1, %struct.LIST_HELP** %5, align 8
  store i8* %2, i8** %6, align 8
  %16 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %4, align 8
  %17 = call i32* @prfs_Store(%struct.PROOFSEARCH_HELP* noundef %16)
  store i32* %17, i32** %15, align 8
  %18 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %4, align 8
  %19 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %20 = call %struct.LIST_HELP* @pcheck_ConvertParentsInSPASSProof(%struct.PROOFSEARCH_HELP* noundef %18, %struct.LIST_HELP* noundef %19)
  store %struct.LIST_HELP* %20, %struct.LIST_HELP** %12, align 8
  %21 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %22 = call i32 @list_Empty(%struct.LIST_HELP* noundef %21)
  %23 = icmp ne i32 %22, 0
  br i1 %23, label %41, label %24

24:                                               ; preds = %3
  %25 = call i32 @puts(i8* noundef getelementptr inbounds ([59 x i8], [59 x i8]* @.str, i64 0, i64 0))
  br label %26

26:                                               ; preds = %36, %24
  %27 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %28 = call i32 @list_Empty(%struct.LIST_HELP* noundef %27)
  %29 = icmp ne i32 %28, 0
  %30 = xor i1 %29, true
  br i1 %30, label %31, label %39

31:                                               ; preds = %26
  %32 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %33 = call i8* @list_Car(%struct.LIST_HELP* noundef %32)
  %34 = ptrtoint i8* %33 to i32
  %35 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str.1, i64 0, i64 0), i32 noundef %34)
  br label %36

36:                                               ; preds = %31
  %37 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %38 = call %struct.LIST_HELP* @list_Pop(%struct.LIST_HELP* noundef %37)
  store %struct.LIST_HELP* %38, %struct.LIST_HELP** %12, align 8
  br label %26, !llvm.loop !4

39:                                               ; preds = %26
  %40 = call i32 @putchar(i32 noundef 10)
  br label %41

41:                                               ; preds = %39, %3
  %42 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %43 = call %struct.LIST_HELP* @list_Copy(%struct.LIST_HELP* noundef %42)
  store %struct.LIST_HELP* %43, %struct.LIST_HELP** %9, align 8
  %44 = call %struct.LIST_HELP* @list_Nil()
  store %struct.LIST_HELP* %44, %struct.LIST_HELP** %7, align 8
  %45 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %4, align 8
  %46 = call %struct.LIST_HELP* @prfs_DocProofClauses(%struct.PROOFSEARCH_HELP* noundef %45)
  %47 = call %struct.LIST_HELP* @list_Copy(%struct.LIST_HELP* noundef %46)
  %48 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %4, align 8
  %49 = call %struct.LIST_HELP* @prfs_UsableClauses(%struct.PROOFSEARCH_HELP* noundef %48)
  %50 = call %struct.LIST_HELP* @list_Copy(%struct.LIST_HELP* noundef %49)
  %51 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %4, align 8
  %52 = call %struct.LIST_HELP* @prfs_WorkedOffClauses(%struct.PROOFSEARCH_HELP* noundef %51)
  %53 = call %struct.LIST_HELP* @list_Copy(%struct.LIST_HELP* noundef %52)
  %54 = call %struct.LIST_HELP* @list_Nconc(%struct.LIST_HELP* noundef %50, %struct.LIST_HELP* noundef %53)
  %55 = call %struct.LIST_HELP* @list_Nconc(%struct.LIST_HELP* noundef %47, %struct.LIST_HELP* noundef %54)
  store %struct.LIST_HELP* %55, %struct.LIST_HELP** %10, align 8
  %56 = call %struct.LIST_HELP* @list_Nil()
  store %struct.LIST_HELP* %56, %struct.LIST_HELP** %14, align 8
  %57 = load %struct.LIST_HELP*, %struct.LIST_HELP** %10, align 8
  store %struct.LIST_HELP* %57, %struct.LIST_HELP** %8, align 8
  br label %58

58:                                               ; preds = %75, %41
  %59 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %60 = call i32 @list_Empty(%struct.LIST_HELP* noundef %59)
  %61 = icmp ne i32 %60, 0
  %62 = xor i1 %61, true
  br i1 %62, label %63, label %78

63:                                               ; preds = %58
  %64 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %65 = call i8* @list_Car(%struct.LIST_HELP* noundef %64)
  %66 = bitcast i8* %65 to %struct.CLAUSE_HELP*
  %67 = call i32 @clause_IsFromSplitting(%struct.CLAUSE_HELP* noundef %66)
  %68 = icmp ne i32 %67, 0
  br i1 %68, label %69, label %74

69:                                               ; preds = %63
  %70 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %71 = call i8* @list_Car(%struct.LIST_HELP* noundef %70)
  %72 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %73 = call %struct.LIST_HELP* @list_Cons(i8* noundef %71, %struct.LIST_HELP* noundef %72)
  store %struct.LIST_HELP* %73, %struct.LIST_HELP** %14, align 8
  br label %74

74:                                               ; preds = %69, %63
  br label %75

75:                                               ; preds = %74
  %76 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %77 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %76)
  store %struct.LIST_HELP* %77, %struct.LIST_HELP** %8, align 8
  br label %58, !llvm.loop !6

78:                                               ; preds = %58
  %79 = load %struct.LIST_HELP*, %struct.LIST_HELP** %9, align 8
  call void @pcheck_ClauseListRemoveFlag(%struct.LIST_HELP* noundef %79, i32 noundef 64)
  %80 = load %struct.LIST_HELP*, %struct.LIST_HELP** %10, align 8
  call void @pcheck_ClauseListRemoveFlag(%struct.LIST_HELP* noundef %80, i32 noundef 64)
  %81 = load %struct.LIST_HELP*, %struct.LIST_HELP** %9, align 8
  call void @pcheck_MarkRecursive(%struct.LIST_HELP* noundef %81)
  %82 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  call void @pcheck_MarkRecursive(%struct.LIST_HELP* noundef %82)
  %83 = call %struct.LIST_HELP* @list_Nil()
  store %struct.LIST_HELP* %83, %struct.LIST_HELP** %7, align 8
  %84 = load %struct.LIST_HELP*, %struct.LIST_HELP** %10, align 8
  store %struct.LIST_HELP* %84, %struct.LIST_HELP** %8, align 8
  br label %85

85:                                               ; preds = %102, %78
  %86 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %87 = call i32 @list_Empty(%struct.LIST_HELP* noundef %86)
  %88 = icmp ne i32 %87, 0
  %89 = xor i1 %88, true
  br i1 %89, label %90, label %105

90:                                               ; preds = %85
  %91 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %92 = call i8* @list_Car(%struct.LIST_HELP* noundef %91)
  %93 = bitcast i8* %92 to %struct.CLAUSE_HELP*
  %94 = call i32 @clause_GetFlag(%struct.CLAUSE_HELP* noundef %93, i32 noundef 64)
  %95 = icmp ne i32 %94, 0
  br i1 %95, label %96, label %101

96:                                               ; preds = %90
  %97 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %98 = call i8* @list_Car(%struct.LIST_HELP* noundef %97)
  %99 = load %struct.LIST_HELP*, %struct.LIST_HELP** %7, align 8
  %100 = call %struct.LIST_HELP* @list_Cons(i8* noundef %98, %struct.LIST_HELP* noundef %99)
  store %struct.LIST_HELP* %100, %struct.LIST_HELP** %7, align 8
  br label %101

101:                                              ; preds = %96, %90
  br label %102

102:                                              ; preds = %101
  %103 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %104 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %103)
  store %struct.LIST_HELP* %104, %struct.LIST_HELP** %8, align 8
  br label %85, !llvm.loop !7

105:                                              ; preds = %85
  %106 = load %struct.LIST_HELP*, %struct.LIST_HELP** %7, align 8
  %107 = load %struct.LIST_HELP*, %struct.LIST_HELP** %9, align 8
  %108 = call %struct.LIST_HELP* @list_Copy(%struct.LIST_HELP* noundef %107)
  %109 = call %struct.LIST_HELP* @list_Nconc(%struct.LIST_HELP* noundef %106, %struct.LIST_HELP* noundef %108)
  store %struct.LIST_HELP* %109, %struct.LIST_HELP** %7, align 8
  %110 = load %struct.LIST_HELP*, %struct.LIST_HELP** %7, align 8
  %111 = call %struct.LIST_HELP* @pcheck_ClauseNumberMergeSort(%struct.LIST_HELP* noundef %110)
  store %struct.LIST_HELP* %111, %struct.LIST_HELP** %7, align 8
  %112 = load %struct.LIST_HELP*, %struct.LIST_HELP** %7, align 8
  %113 = call %struct.LIST_HELP* @pcheck_ReduceSPASSProof(%struct.LIST_HELP* noundef %112)
  store %struct.LIST_HELP* %113, %struct.LIST_HELP** %11, align 8
  %114 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  %115 = call i32 @pcheck_SeqProofDepth(%struct.LIST_HELP* noundef %114)
  call void @dp_SetProofDepth(i32 noundef %115)
  %116 = load %struct.LIST_HELP*, %struct.LIST_HELP** %10, align 8
  %117 = call %struct.LIST_HELP* @pcheck_ParentPointersToParentNumbers(%struct.LIST_HELP* noundef %116)
  %118 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %119 = call %struct.LIST_HELP* @pcheck_ParentPointersToParentNumbers(%struct.LIST_HELP* noundef %118)
  %120 = call %struct.LIST_HELP* @list_Nil()
  store %struct.LIST_HELP* %120, %struct.LIST_HELP** %13, align 8
  %121 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  store %struct.LIST_HELP* %121, %struct.LIST_HELP** %8, align 8
  br label %122

122:                                              ; preds = %139, %105
  %123 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %124 = call i32 @list_Empty(%struct.LIST_HELP* noundef %123)
  %125 = icmp ne i32 %124, 0
  %126 = xor i1 %125, true
  br i1 %126, label %127, label %142

127:                                              ; preds = %122
  %128 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %129 = call i8* @list_Car(%struct.LIST_HELP* noundef %128)
  %130 = bitcast i8* %129 to %struct.CLAUSE_HELP*
  %131 = call i32 @clause_GetFlag(%struct.CLAUSE_HELP* noundef %130, i32 noundef 128)
  %132 = icmp ne i32 %131, 0
  br i1 %132, label %133, label %138

133:                                              ; preds = %127
  %134 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %135 = call i8* @list_Car(%struct.LIST_HELP* noundef %134)
  %136 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  %137 = call %struct.LIST_HELP* @list_Cons(i8* noundef %135, %struct.LIST_HELP* noundef %136)
  store %struct.LIST_HELP* %137, %struct.LIST_HELP** %13, align 8
  br label %138

138:                                              ; preds = %133, %127
  br label %139

139:                                              ; preds = %138
  %140 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %141 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %140)
  store %struct.LIST_HELP* %141, %struct.LIST_HELP** %8, align 8
  br label %122, !llvm.loop !8

142:                                              ; preds = %122
  %143 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  %144 = call i32 @list_Empty(%struct.LIST_HELP* noundef %143)
  %145 = icmp ne i32 %144, 0
  br i1 %145, label %165, label %146

146:                                              ; preds = %142
  %147 = call i32 @puts(i8* noundef getelementptr inbounds ([70 x i8], [70 x i8]* @.str.2, i64 0, i64 0))
  %148 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  store %struct.LIST_HELP* %148, %struct.LIST_HELP** %8, align 8
  br label %149

149:                                              ; preds = %160, %146
  %150 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %151 = call i32 @list_Empty(%struct.LIST_HELP* noundef %150)
  %152 = icmp ne i32 %151, 0
  %153 = xor i1 %152, true
  br i1 %153, label %154, label %163

154:                                              ; preds = %149
  %155 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %156 = call i8* @list_Car(%struct.LIST_HELP* noundef %155)
  %157 = bitcast i8* %156 to %struct.CLAUSE_HELP*
  %158 = call i32 @clause_Number(%struct.CLAUSE_HELP* noundef %157)
  %159 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str.1, i64 0, i64 0), i32 noundef %158)
  br label %160

160:                                              ; preds = %154
  %161 = load %struct.LIST_HELP*, %struct.LIST_HELP** %8, align 8
  %162 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %161)
  store %struct.LIST_HELP* %162, %struct.LIST_HELP** %8, align 8
  br label %149, !llvm.loop !9

163:                                              ; preds = %149
  %164 = call i32 @putchar(i32 noundef 10)
  br label %165

165:                                              ; preds = %163, %142
  %166 = call i32 @dp_ProofDepth()
  %167 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  %168 = call i32 @list_Length(%struct.LIST_HELP* noundef %167)
  %169 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([46 x i8], [46 x i8]* @.str.3, i64 0, i64 0), i32 noundef %166, i32 noundef %168)
  %170 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  call void @clause_ListPrint(%struct.LIST_HELP* noundef %170)
  %171 = load i32*, i32** %15, align 8
  %172 = call i32 @flag_GetFlagValue(i32* noundef %171, i32 noundef 31)
  %173 = icmp ne i32 %172, 0
  br i1 %173, label %174, label %180

174:                                              ; preds = %165
  %175 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  %176 = load i8*, i8** %6, align 8
  %177 = load i32*, i32** %15, align 8
  %178 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %4, align 8
  %179 = call i32* @prfs_Precedence(%struct.PROOFSEARCH_HELP* noundef %178)
  call void @dp_FPrintDFGProof(%struct.LIST_HELP* noundef %175, i8* noundef %176, i32* noundef %177, i32* noundef %179)
  br label %180

180:                                              ; preds = %174, %165
  %181 = load %struct._IO_FILE*, %struct._IO_FILE** @stdout, align 8
  %182 = call i32 @fflush(%struct._IO_FILE* noundef %181)
  %183 = load %struct.LIST_HELP*, %struct.LIST_HELP** %9, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %183)
  %184 = load %struct.LIST_HELP*, %struct.LIST_HELP** %10, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %184)
  %185 = load %struct.LIST_HELP*, %struct.LIST_HELP** %7, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %185)
  %186 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %186)
  %187 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %187)
  %188 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  ret %struct.LIST_HELP* %188
}

; Function Attrs: noinline nounwind uwtable
define internal i32* @prfs_Store(%struct.PROOFSEARCH_HELP* noundef %0) #0 {
  %2 = alloca %struct.PROOFSEARCH_HELP*, align 8
  store %struct.PROOFSEARCH_HELP* %0, %struct.PROOFSEARCH_HELP** %2, align 8
  %3 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.PROOFSEARCH_HELP, %struct.PROOFSEARCH_HELP* %3, i32 0, i32 14
  %5 = load i32*, i32** %4, align 8
  ret i32* %5
}

declare dso_local %struct.LIST_HELP* @pcheck_ConvertParentsInSPASSProof(%struct.PROOFSEARCH_HELP* noundef, %struct.LIST_HELP* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal i32 @list_Empty(%struct.LIST_HELP* noundef %0) #0 {
  %2 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %2, align 8
  %3 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  %4 = icmp eq %struct.LIST_HELP* %3, null
  %5 = zext i1 %4 to i32
  ret i32 %5
}

declare dso_local i32 @puts(i8* noundef) #1

declare dso_local i32 @printf(i8* noundef, ...) #1

; Function Attrs: noinline nounwind uwtable
define internal i8* @list_Car(%struct.LIST_HELP* noundef %0) #0 {
  %2 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %2, align 8
  %3 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.LIST_HELP, %struct.LIST_HELP* %3, i32 0, i32 1
  %5 = load i8*, i8** %4, align 8
  ret i8* %5
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @list_Pop(%struct.LIST_HELP* noundef %0) #0 {
  %2 = alloca %struct.LIST_HELP*, align 8
  %3 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %2, align 8
  %4 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  store %struct.LIST_HELP* %4, %struct.LIST_HELP** %3, align 8
  %5 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  %6 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %5)
  store %struct.LIST_HELP* %6, %struct.LIST_HELP** %2, align 8
  %7 = load %struct.LIST_HELP*, %struct.LIST_HELP** %3, align 8
  call void @list_Free(%struct.LIST_HELP* noundef %7)
  %8 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  ret %struct.LIST_HELP* %8
}

declare dso_local i32 @putchar(i32 noundef) #1

declare dso_local %struct.LIST_HELP* @list_Copy(%struct.LIST_HELP* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @list_Nil() #0 {
  ret %struct.LIST_HELP* null
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @list_Nconc(%struct.LIST_HELP* noundef %0, %struct.LIST_HELP* noundef %1) #0 {
  %3 = alloca %struct.LIST_HELP*, align 8
  %4 = alloca %struct.LIST_HELP*, align 8
  %5 = alloca %struct.LIST_HELP*, align 8
  %6 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %4, align 8
  store %struct.LIST_HELP* %1, %struct.LIST_HELP** %5, align 8
  %7 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  %8 = call i32 @list_Empty(%struct.LIST_HELP* noundef %7)
  %9 = icmp ne i32 %8, 0
  br i1 %9, label %10, label %12

10:                                               ; preds = %2
  %11 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  store %struct.LIST_HELP* %11, %struct.LIST_HELP** %3, align 8
  br label %36

12:                                               ; preds = %2
  %13 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %14 = call i32 @list_Empty(%struct.LIST_HELP* noundef %13)
  %15 = icmp ne i32 %14, 0
  br i1 %15, label %16, label %18

16:                                               ; preds = %12
  %17 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  store %struct.LIST_HELP* %17, %struct.LIST_HELP** %3, align 8
  br label %36

18:                                               ; preds = %12
  %19 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  store %struct.LIST_HELP* %19, %struct.LIST_HELP** %6, align 8
  %20 = load %struct.LIST_HELP*, %struct.LIST_HELP** %6, align 8
  store %struct.LIST_HELP* %20, %struct.LIST_HELP** %4, align 8
  br label %21

21:                                               ; preds = %28, %18
  %22 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  %23 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %22)
  %24 = call i32 @list_Empty(%struct.LIST_HELP* noundef %23)
  %25 = icmp ne i32 %24, 0
  %26 = xor i1 %25, true
  br i1 %26, label %27, label %31

27:                                               ; preds = %21
  br label %28

28:                                               ; preds = %27
  %29 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  %30 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %29)
  store %struct.LIST_HELP* %30, %struct.LIST_HELP** %4, align 8
  br label %21, !llvm.loop !10

31:                                               ; preds = %21
  %32 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %33 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  %34 = getelementptr inbounds %struct.LIST_HELP, %struct.LIST_HELP* %33, i32 0, i32 0
  store %struct.LIST_HELP* %32, %struct.LIST_HELP** %34, align 8
  %35 = load %struct.LIST_HELP*, %struct.LIST_HELP** %6, align 8
  store %struct.LIST_HELP* %35, %struct.LIST_HELP** %3, align 8
  br label %36

36:                                               ; preds = %31, %16, %10
  %37 = load %struct.LIST_HELP*, %struct.LIST_HELP** %3, align 8
  ret %struct.LIST_HELP* %37
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @prfs_DocProofClauses(%struct.PROOFSEARCH_HELP* noundef %0) #0 {
  %2 = alloca %struct.PROOFSEARCH_HELP*, align 8
  store %struct.PROOFSEARCH_HELP* %0, %struct.PROOFSEARCH_HELP** %2, align 8
  %3 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.PROOFSEARCH_HELP, %struct.PROOFSEARCH_HELP* %3, i32 0, i32 12
  %5 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  ret %struct.LIST_HELP* %5
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @prfs_UsableClauses(%struct.PROOFSEARCH_HELP* noundef %0) #0 {
  %2 = alloca %struct.PROOFSEARCH_HELP*, align 8
  store %struct.PROOFSEARCH_HELP* %0, %struct.PROOFSEARCH_HELP** %2, align 8
  %3 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.PROOFSEARCH_HELP, %struct.PROOFSEARCH_HELP* %3, i32 0, i32 7
  %5 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  ret %struct.LIST_HELP* %5
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @prfs_WorkedOffClauses(%struct.PROOFSEARCH_HELP* noundef %0) #0 {
  %2 = alloca %struct.PROOFSEARCH_HELP*, align 8
  store %struct.PROOFSEARCH_HELP* %0, %struct.PROOFSEARCH_HELP** %2, align 8
  %3 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.PROOFSEARCH_HELP, %struct.PROOFSEARCH_HELP* %3, i32 0, i32 5
  %5 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  ret %struct.LIST_HELP* %5
}

; Function Attrs: noinline nounwind uwtable
define internal i32 @clause_IsFromSplitting(%struct.CLAUSE_HELP* noundef %0) #0 {
  %2 = alloca %struct.CLAUSE_HELP*, align 8
  store %struct.CLAUSE_HELP* %0, %struct.CLAUSE_HELP** %2, align 8
  %3 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.CLAUSE_HELP, %struct.CLAUSE_HELP* %3, i32 0, i32 14
  %5 = load i32, i32* %4, align 4
  %6 = icmp eq i32 %5, 15
  %7 = zext i1 %6 to i32
  ret i32 %7
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @list_Cons(i8* noundef %0, %struct.LIST_HELP* noundef %1) #0 {
  %3 = alloca i8*, align 8
  %4 = alloca %struct.LIST_HELP*, align 8
  %5 = alloca %struct.LIST_HELP*, align 8
  store i8* %0, i8** %3, align 8
  store %struct.LIST_HELP* %1, %struct.LIST_HELP** %4, align 8
  %6 = call i8* @memory_Malloc(i32 noundef 16)
  %7 = bitcast i8* %6 to %struct.LIST_HELP*
  store %struct.LIST_HELP* %7, %struct.LIST_HELP** %5, align 8
  %8 = load i8*, i8** %3, align 8
  %9 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %10 = getelementptr inbounds %struct.LIST_HELP, %struct.LIST_HELP* %9, i32 0, i32 1
  store i8* %8, i8** %10, align 8
  %11 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  %12 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  %13 = getelementptr inbounds %struct.LIST_HELP, %struct.LIST_HELP* %12, i32 0, i32 0
  store %struct.LIST_HELP* %11, %struct.LIST_HELP** %13, align 8
  %14 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  ret %struct.LIST_HELP* %14
}

; Function Attrs: noinline nounwind uwtable
define internal %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %0) #0 {
  %2 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %2, align 8
  %3 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.LIST_HELP, %struct.LIST_HELP* %3, i32 0, i32 0
  %5 = load %struct.LIST_HELP*, %struct.LIST_HELP** %4, align 8
  ret %struct.LIST_HELP* %5
}

declare dso_local void @pcheck_ClauseListRemoveFlag(%struct.LIST_HELP* noundef, i32 noundef) #1

declare dso_local void @pcheck_MarkRecursive(%struct.LIST_HELP* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal i32 @clause_GetFlag(%struct.CLAUSE_HELP* noundef %0, i32 noundef %1) #0 {
  %3 = alloca %struct.CLAUSE_HELP*, align 8
  %4 = alloca i32, align 4
  store %struct.CLAUSE_HELP* %0, %struct.CLAUSE_HELP** %3, align 8
  store i32 %1, i32* %4, align 4
  %5 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %3, align 8
  %6 = getelementptr inbounds %struct.CLAUSE_HELP, %struct.CLAUSE_HELP* %5, i32 0, i32 8
  %7 = load i32, i32* %6, align 8
  %8 = load i32, i32* %4, align 4
  %9 = and i32 %7, %8
  %10 = icmp ne i32 %9, 0
  %11 = zext i1 %10 to i32
  ret i32 %11
}

declare dso_local %struct.LIST_HELP* @pcheck_ClauseNumberMergeSort(%struct.LIST_HELP* noundef) #1

declare dso_local %struct.LIST_HELP* @pcheck_ReduceSPASSProof(%struct.LIST_HELP* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal void @dp_SetProofDepth(i32 noundef %0) #0 {
  %2 = alloca i32, align 4
  store i32 %0, i32* %2, align 4
  %3 = load i32, i32* %2, align 4
  store i32 %3, i32* @dp_DEPTH, align 4
  ret void
}

declare dso_local i32 @pcheck_SeqProofDepth(%struct.LIST_HELP* noundef) #1

declare dso_local %struct.LIST_HELP* @pcheck_ParentPointersToParentNumbers(%struct.LIST_HELP* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal i32 @clause_Number(%struct.CLAUSE_HELP* noundef %0) #0 {
  %2 = alloca %struct.CLAUSE_HELP*, align 8
  store %struct.CLAUSE_HELP* %0, %struct.CLAUSE_HELP** %2, align 8
  %3 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.CLAUSE_HELP, %struct.CLAUSE_HELP* %3, i32 0, i32 0
  %5 = load i32, i32* %4, align 8
  ret i32 %5
}

; Function Attrs: noinline nounwind uwtable
define internal i32 @dp_ProofDepth() #0 {
  %1 = load i32, i32* @dp_DEPTH, align 4
  ret i32 %1
}

declare dso_local i32 @list_Length(%struct.LIST_HELP* noundef) #1

declare dso_local void @clause_ListPrint(%struct.LIST_HELP* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal i32 @flag_GetFlagValue(i32* noundef %0, i32 noundef %1) #0 {
  %3 = alloca i32*, align 8
  %4 = alloca i32, align 4
  %5 = alloca i32, align 4
  store i32* %0, i32** %3, align 8
  store i32 %1, i32* %4, align 4
  %6 = load i32, i32* %4, align 4
  call void @flag_CheckFlagIdInRange(i32 noundef %6)
  %7 = load i32*, i32** %3, align 8
  %8 = load i32, i32* %4, align 4
  %9 = zext i32 %8 to i64
  %10 = getelementptr inbounds i32, i32* %7, i64 %9
  %11 = load i32, i32* %10, align 4
  store i32 %11, i32* %5, align 4
  %12 = load i32, i32* %5, align 4
  ret i32 %12
}

; Function Attrs: noinline nounwind uwtable
define internal void @dp_FPrintDFGProof(%struct.LIST_HELP* noundef %0, i8* noundef %1, i32* noundef %2, i32* noundef %3) #0 {
  %5 = alloca %struct.LIST_HELP*, align 8
  %6 = alloca i8*, align 8
  %7 = alloca i32*, align 8
  %8 = alloca i32*, align 8
  %9 = alloca %struct._IO_FILE*, align 8
  %10 = alloca %struct.CLAUSE_HELP*, align 8
  %11 = alloca %struct.LIST_HELP*, align 8
  %12 = alloca %struct.LIST_HELP*, align 8
  %13 = alloca %struct.LIST_HELP*, align 8
  %14 = alloca %struct.LIST_HELP*, align 8
  %15 = alloca i8*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %5, align 8
  store i8* %1, i8** %6, align 8
  store i32* %2, i32** %7, align 8
  store i32* %3, i32** %8, align 8
  %16 = call %struct.LIST_HELP* @list_Nil()
  store %struct.LIST_HELP* %16, %struct.LIST_HELP** %13, align 8
  store %struct.LIST_HELP* %16, %struct.LIST_HELP** %12, align 8
  store %struct.LIST_HELP* %16, %struct.LIST_HELP** %11, align 8
  %17 = load i8*, i8** %6, align 8
  %18 = call i64 @strlen(i8* noundef %17) #4
  %19 = add i64 %18, 5
  %20 = mul i64 1, %19
  %21 = trunc i64 %20 to i32
  %22 = call i8* @memory_Malloc(i32 noundef %21)
  store i8* %22, i8** %15, align 8
  %23 = load i8*, i8** %15, align 8
  %24 = load i8*, i8** %6, align 8
  %25 = call i32 (i8*, i8*, ...) @sprintf(i8* noundef %23, i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @.str.4, i64 0, i64 0), i8* noundef %24) #5
  %26 = load i8*, i8** %15, align 8
  %27 = call %struct._IO_FILE* @misc_OpenFile(i8* noundef %26, i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @.str.5, i64 0, i64 0))
  store %struct._IO_FILE* %27, %struct._IO_FILE** %9, align 8
  %28 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %29 = call i32 @fputs(i8* noundef getelementptr inbounds ([26 x i8], [26 x i8]* @.str.6, i64 0, i64 0), %struct._IO_FILE* noundef %28)
  %30 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %31 = call i32 @fputs(i8* noundef getelementptr inbounds ([23 x i8], [23 x i8]* @.str.7, i64 0, i64 0), %struct._IO_FILE* noundef %30)
  %32 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %33 = call i32 @fputs(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @.str.8, i64 0, i64 0), %struct._IO_FILE* noundef %32)
  %34 = load i8*, i8** %6, align 8
  %35 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %36 = call i32 @fputs(i8* noundef %34, %struct._IO_FILE* noundef %35)
  %37 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %38 = call i32 @fputs(i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @.str.9, i64 0, i64 0), %struct._IO_FILE* noundef %37)
  %39 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %40 = call i32 @fputs(i8* noundef getelementptr inbounds ([16 x i8], [16 x i8]* @.str.10, i64 0, i64 0), %struct._IO_FILE* noundef %39)
  %41 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %42 = call i32 @fputs(i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @.str.11, i64 0, i64 0), %struct._IO_FILE* noundef %41)
  %43 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %44 = call i32 @fputs(i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @.str.9, i64 0, i64 0), %struct._IO_FILE* noundef %43)
  %45 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %46 = call i32 @fputs(i8* noundef getelementptr inbounds ([24 x i8], [24 x i8]* @.str.12, i64 0, i64 0), %struct._IO_FILE* noundef %45)
  %47 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %48 = call i32 @fputs(i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str.13, i64 0, i64 0), %struct._IO_FILE* noundef %47)
  %49 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %50 = call i32 @fputs(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @.str.14, i64 0, i64 0), %struct._IO_FILE* noundef %49)
  %51 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %52 = call i32 @fputs(i8* noundef getelementptr inbounds ([18 x i8], [18 x i8]* @.str.15, i64 0, i64 0), %struct._IO_FILE* noundef %51)
  %53 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  call void @fol_FPrintDFGSignature(%struct._IO_FILE* noundef %53)
  %54 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %55 = call i32 @fputs(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @.str.14, i64 0, i64 0), %struct._IO_FILE* noundef %54)
  %56 = load %struct.LIST_HELP*, %struct.LIST_HELP** %5, align 8
  store %struct.LIST_HELP* %56, %struct.LIST_HELP** %14, align 8
  br label %57

57:                                               ; preds = %90, %4
  %58 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %59 = call i32 @list_Empty(%struct.LIST_HELP* noundef %58)
  %60 = icmp ne i32 %59, 0
  %61 = xor i1 %60, true
  br i1 %61, label %62, label %93

62:                                               ; preds = %57
  %63 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %64 = call i8* @list_Car(%struct.LIST_HELP* noundef %63)
  %65 = bitcast i8* %64 to %struct.CLAUSE_HELP*
  store %struct.CLAUSE_HELP* %65, %struct.CLAUSE_HELP** %10, align 8
  %66 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %10, align 8
  %67 = call i32 @clause_IsFromInput(%struct.CLAUSE_HELP* noundef %66)
  %68 = icmp ne i32 %67, 0
  br i1 %68, label %69, label %84

69:                                               ; preds = %62
  %70 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %10, align 8
  %71 = call i32 @clause_GetFlag(%struct.CLAUSE_HELP* noundef %70, i32 noundef 8)
  %72 = icmp ne i32 %71, 0
  br i1 %72, label %73, label %78

73:                                               ; preds = %69
  %74 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %10, align 8
  %75 = bitcast %struct.CLAUSE_HELP* %74 to i8*
  %76 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %77 = call %struct.LIST_HELP* @list_Cons(i8* noundef %75, %struct.LIST_HELP* noundef %76)
  store %struct.LIST_HELP* %77, %struct.LIST_HELP** %12, align 8
  br label %83

78:                                               ; preds = %69
  %79 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %10, align 8
  %80 = bitcast %struct.CLAUSE_HELP* %79 to i8*
  %81 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  %82 = call %struct.LIST_HELP* @list_Cons(i8* noundef %80, %struct.LIST_HELP* noundef %81)
  store %struct.LIST_HELP* %82, %struct.LIST_HELP** %11, align 8
  br label %83

83:                                               ; preds = %78, %73
  br label %89

84:                                               ; preds = %62
  %85 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %10, align 8
  %86 = bitcast %struct.CLAUSE_HELP* %85 to i8*
  %87 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  %88 = call %struct.LIST_HELP* @list_Cons(i8* noundef %86, %struct.LIST_HELP* noundef %87)
  store %struct.LIST_HELP* %88, %struct.LIST_HELP** %13, align 8
  br label %89

89:                                               ; preds = %84, %83
  br label %90

90:                                               ; preds = %89
  %91 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %92 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %91)
  store %struct.LIST_HELP* %92, %struct.LIST_HELP** %14, align 8
  br label %57, !llvm.loop !11

93:                                               ; preds = %57
  %94 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %95 = call %struct.LIST_HELP* @list_NReverse(%struct.LIST_HELP* noundef %94)
  store %struct.LIST_HELP* %95, %struct.LIST_HELP** %12, align 8
  %96 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  %97 = call %struct.LIST_HELP* @list_NReverse(%struct.LIST_HELP* noundef %96)
  store %struct.LIST_HELP* %97, %struct.LIST_HELP** %11, align 8
  %98 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  %99 = call %struct.LIST_HELP* @list_NReverse(%struct.LIST_HELP* noundef %98)
  store %struct.LIST_HELP* %99, %struct.LIST_HELP** %13, align 8
  %100 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %101 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  %102 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  %103 = load i32*, i32** %7, align 8
  %104 = load i32*, i32** %8, align 8
  call void @clause_FPrintCnfDFG(%struct._IO_FILE* noundef %100, i32 noundef 0, %struct.LIST_HELP* noundef %101, %struct.LIST_HELP* noundef %102, i32* noundef %103, i32* noundef %104)
  %105 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %106 = call i32 @fputs(i8* noundef getelementptr inbounds ([24 x i8], [24 x i8]* @.str.16, i64 0, i64 0), %struct._IO_FILE* noundef %105)
  %107 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  store %struct.LIST_HELP* %107, %struct.LIST_HELP** %14, align 8
  br label %108

108:                                              ; preds = %118, %93
  %109 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %110 = call i32 @list_Empty(%struct.LIST_HELP* noundef %109)
  %111 = icmp ne i32 %110, 0
  %112 = xor i1 %111, true
  br i1 %112, label %113, label %121

113:                                              ; preds = %108
  %114 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %115 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %116 = call i8* @list_Car(%struct.LIST_HELP* noundef %115)
  %117 = bitcast i8* %116 to %struct.CLAUSE_HELP*
  call void @clause_FPrintDFGStep(%struct._IO_FILE* noundef %114, %struct.CLAUSE_HELP* noundef %117, i32 noundef 1)
  br label %118

118:                                              ; preds = %113
  %119 = load %struct.LIST_HELP*, %struct.LIST_HELP** %14, align 8
  %120 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %119)
  store %struct.LIST_HELP* %120, %struct.LIST_HELP** %14, align 8
  br label %108, !llvm.loop !12

121:                                              ; preds = %108
  %122 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %123 = call i32 @fputs(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @.str.14, i64 0, i64 0), %struct._IO_FILE* noundef %122)
  %124 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %125 = call i32 @fputs(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @.str.17, i64 0, i64 0), %struct._IO_FILE* noundef %124)
  %126 = load %struct._IO_FILE*, %struct._IO_FILE** %9, align 8
  %127 = load i8*, i8** %15, align 8
  call void @misc_CloseFile(%struct._IO_FILE* noundef %126, i8* noundef %127)
  %128 = load %struct._IO_FILE*, %struct._IO_FILE** @stdout, align 8
  %129 = call i32 @fputs(i8* noundef getelementptr inbounds ([24 x i8], [24 x i8]* @.str.18, i64 0, i64 0), %struct._IO_FILE* noundef %128)
  %130 = load i8*, i8** %15, align 8
  %131 = call i32 @puts(i8* noundef %130)
  %132 = load %struct.LIST_HELP*, %struct.LIST_HELP** %12, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %132)
  %133 = load %struct.LIST_HELP*, %struct.LIST_HELP** %11, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %133)
  %134 = load %struct.LIST_HELP*, %struct.LIST_HELP** %13, align 8
  call void @list_Delete(%struct.LIST_HELP* noundef %134)
  %135 = load i8*, i8** %15, align 8
  %136 = load i8*, i8** %6, align 8
  %137 = call i64 @strlen(i8* noundef %136) #4
  %138 = add i64 %137, 5
  %139 = mul i64 1, %138
  %140 = trunc i64 %139 to i32
  call void @memory_Free(i8* noundef %135, i32 noundef %140)
  ret void
}

; Function Attrs: noinline nounwind uwtable
define internal i32* @prfs_Precedence(%struct.PROOFSEARCH_HELP* noundef %0) #0 {
  %2 = alloca %struct.PROOFSEARCH_HELP*, align 8
  store %struct.PROOFSEARCH_HELP* %0, %struct.PROOFSEARCH_HELP** %2, align 8
  %3 = load %struct.PROOFSEARCH_HELP*, %struct.PROOFSEARCH_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.PROOFSEARCH_HELP, %struct.PROOFSEARCH_HELP* %3, i32 0, i32 13
  %5 = load i32*, i32** %4, align 8
  ret i32* %5
}

declare dso_local i32 @fflush(%struct._IO_FILE* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal void @list_Delete(%struct.LIST_HELP* noundef %0) #0 {
  %2 = alloca %struct.LIST_HELP*, align 8
  %3 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %2, align 8
  %4 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  store %struct.LIST_HELP* %4, %struct.LIST_HELP** %3, align 8
  br label %5

5:                                                ; preds = %10, %1
  %6 = load %struct.LIST_HELP*, %struct.LIST_HELP** %3, align 8
  %7 = call i32 @list_Empty(%struct.LIST_HELP* noundef %6)
  %8 = icmp ne i32 %7, 0
  %9 = xor i1 %8, true
  br i1 %9, label %10, label %15

10:                                               ; preds = %5
  %11 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  %12 = call %struct.LIST_HELP* @list_Cdr(%struct.LIST_HELP* noundef %11)
  store %struct.LIST_HELP* %12, %struct.LIST_HELP** %2, align 8
  %13 = load %struct.LIST_HELP*, %struct.LIST_HELP** %3, align 8
  call void @list_Free(%struct.LIST_HELP* noundef %13)
  %14 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  store %struct.LIST_HELP* %14, %struct.LIST_HELP** %3, align 8
  br label %5, !llvm.loop !13

15:                                               ; preds = %5
  ret void
}

; Function Attrs: noinline nounwind uwtable
define internal void @list_Free(%struct.LIST_HELP* noundef %0) #0 {
  %2 = alloca %struct.LIST_HELP*, align 8
  store %struct.LIST_HELP* %0, %struct.LIST_HELP** %2, align 8
  %3 = load %struct.LIST_HELP*, %struct.LIST_HELP** %2, align 8
  %4 = bitcast %struct.LIST_HELP* %3 to i8*
  call void @memory_Free(i8* noundef %4, i32 noundef 16)
  ret void
}

; Function Attrs: noinline nounwind uwtable
define internal void @memory_Free(i8* noundef %0, i32 noundef %1) #0 {
  %3 = alloca i8*, align 8
  %4 = alloca i32, align 4
  %5 = alloca i32, align 4
  %6 = alloca %struct.MEMORY_BIGBLOCKHEADERHELP*, align 8
  store i8* %0, i8** %3, align 8
  store i32 %1, i32* %4, align 4
  %7 = load i32, i32* %4, align 4
  %8 = call i32 @memory_LookupRealBlockSize(i32 noundef %7)
  store i32 %8, i32* %5, align 4
  %9 = load i32, i32* %4, align 4
  %10 = icmp uge i32 %9, 1024
  br i1 %10, label %11, label %69

11:                                               ; preds = %2
  %12 = load i8*, i8** %3, align 8
  %13 = load i32, i32* @memory_OFFSET, align 4
  %14 = zext i32 %13 to i64
  %15 = sub i64 0, %14
  %16 = getelementptr inbounds i8, i8* %12, i64 %15
  %17 = getelementptr inbounds i8, i8* %16, i64 -16
  %18 = bitcast i8* %17 to %struct.MEMORY_BIGBLOCKHEADERHELP*
  store %struct.MEMORY_BIGBLOCKHEADERHELP* %18, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %19 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %20 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %19, i32 0, i32 0
  %21 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %20, align 8
  %22 = icmp ne %struct.MEMORY_BIGBLOCKHEADERHELP* %21, null
  br i1 %22, label %23, label %31

23:                                               ; preds = %11
  %24 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %25 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %24, i32 0, i32 1
  %26 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %25, align 8
  %27 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %28 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %27, i32 0, i32 0
  %29 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %28, align 8
  %30 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %29, i32 0, i32 1
  store %struct.MEMORY_BIGBLOCKHEADERHELP* %26, %struct.MEMORY_BIGBLOCKHEADERHELP** %30, align 8
  br label %35

31:                                               ; preds = %11
  %32 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %33 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %32, i32 0, i32 1
  %34 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %33, align 8
  store %struct.MEMORY_BIGBLOCKHEADERHELP* %34, %struct.MEMORY_BIGBLOCKHEADERHELP** @memory_BIGBLOCKS, align 8
  br label %35

35:                                               ; preds = %31, %23
  %36 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %37 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %36, i32 0, i32 1
  %38 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %37, align 8
  %39 = icmp ne %struct.MEMORY_BIGBLOCKHEADERHELP* %38, null
  br i1 %39, label %40, label %48

40:                                               ; preds = %35
  %41 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %42 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %41, i32 0, i32 0
  %43 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %42, align 8
  %44 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %6, align 8
  %45 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %44, i32 0, i32 1
  %46 = load %struct.MEMORY_BIGBLOCKHEADERHELP*, %struct.MEMORY_BIGBLOCKHEADERHELP** %45, align 8
  %47 = getelementptr inbounds %struct.MEMORY_BIGBLOCKHEADERHELP, %struct.MEMORY_BIGBLOCKHEADERHELP* %46, i32 0, i32 0
  store %struct.MEMORY_BIGBLOCKHEADERHELP* %43, %struct.MEMORY_BIGBLOCKHEADERHELP** %47, align 8
  br label %48

48:                                               ; preds = %40, %35
  %49 = load i32, i32* %5, align 4
  %50 = load i32, i32* @memory_MARKSIZE, align 4
  %51 = add i32 %49, %50
  %52 = zext i32 %51 to i64
  %53 = add i64 %52, 16
  %54 = load i64, i64* @memory_FREEDBYTES, align 8
  %55 = add i64 %54, %53
  store i64 %55, i64* @memory_FREEDBYTES, align 8
  %56 = load i64, i64* @memory_MAXMEM, align 8
  %57 = icmp sge i64 %56, 0
  br i1 %57, label %58, label %66

58:                                               ; preds = %48
  %59 = load i32, i32* %5, align 4
  %60 = load i32, i32* @memory_MARKSIZE, align 4
  %61 = add i32 %59, %60
  %62 = zext i32 %61 to i64
  %63 = add i64 %62, 16
  %64 = load i64, i64* @memory_MAXMEM, align 8
  %65 = add i64 %64, %63
  store i64 %65, i64* @memory_MAXMEM, align 8
  br label %66

66:                                               ; preds = %58, %48
  %67 = load i8*, i8** %3, align 8
  %68 = getelementptr inbounds i8, i8* %67, i64 -16
  call void @free(i8* noundef %68) #5
  br label %93

69:                                               ; preds = %2
  %70 = load i32, i32* %4, align 4
  %71 = zext i32 %70 to i64
  %72 = getelementptr inbounds [0 x %struct.MEMORY_RESOURCEHELP*], [0 x %struct.MEMORY_RESOURCEHELP*]* @memory_ARRAY, i64 0, i64 %71
  %73 = load %struct.MEMORY_RESOURCEHELP*, %struct.MEMORY_RESOURCEHELP** %72, align 8
  %74 = getelementptr inbounds %struct.MEMORY_RESOURCEHELP, %struct.MEMORY_RESOURCEHELP* %73, i32 0, i32 4
  %75 = load i32, i32* %74, align 8
  %76 = sext i32 %75 to i64
  %77 = load i64, i64* @memory_FREEDBYTES, align 8
  %78 = add i64 %77, %76
  store i64 %78, i64* @memory_FREEDBYTES, align 8
  %79 = load i32, i32* %4, align 4
  %80 = zext i32 %79 to i64
  %81 = getelementptr inbounds [0 x %struct.MEMORY_RESOURCEHELP*], [0 x %struct.MEMORY_RESOURCEHELP*]* @memory_ARRAY, i64 0, i64 %80
  %82 = load %struct.MEMORY_RESOURCEHELP*, %struct.MEMORY_RESOURCEHELP** %81, align 8
  %83 = getelementptr inbounds %struct.MEMORY_RESOURCEHELP, %struct.MEMORY_RESOURCEHELP* %82, i32 0, i32 0
  %84 = load i8*, i8** %83, align 8
  %85 = load i8*, i8** %3, align 8
  %86 = bitcast i8* %85 to i8**
  store i8* %84, i8** %86, align 8
  %87 = load i8*, i8** %3, align 8
  %88 = load i32, i32* %4, align 4
  %89 = zext i32 %88 to i64
  %90 = getelementptr inbounds [0 x %struct.MEMORY_RESOURCEHELP*], [0 x %struct.MEMORY_RESOURCEHELP*]* @memory_ARRAY, i64 0, i64 %89
  %91 = load %struct.MEMORY_RESOURCEHELP*, %struct.MEMORY_RESOURCEHELP** %90, align 8
  %92 = getelementptr inbounds %struct.MEMORY_RESOURCEHELP, %struct.MEMORY_RESOURCEHELP* %91, i32 0, i32 0
  store i8* %87, i8** %92, align 8
  br label %93

93:                                               ; preds = %69, %66
  ret void
}

; Function Attrs: noinline nounwind uwtable
define internal i32 @memory_LookupRealBlockSize(i32 noundef %0) #0 {
  %2 = alloca i32, align 4
  %3 = alloca i32, align 4
  store i32 %0, i32* %2, align 4
  %4 = load i32, i32* %2, align 4
  %5 = icmp ult i32 %4, 1024
  br i1 %5, label %6, label %13

6:                                                ; preds = %1
  %7 = load i32, i32* %2, align 4
  %8 = zext i32 %7 to i64
  %9 = getelementptr inbounds [0 x %struct.MEMORY_RESOURCEHELP*], [0 x %struct.MEMORY_RESOURCEHELP*]* @memory_ARRAY, i64 0, i64 %8
  %10 = load %struct.MEMORY_RESOURCEHELP*, %struct.MEMORY_RESOURCEHELP** %9, align 8
  %11 = getelementptr inbounds %struct.MEMORY_RESOURCEHELP, %struct.MEMORY_RESOURCEHELP* %10, i32 0, i32 5
  %12 = load i32, i32* %11, align 4
  store i32 %12, i32* %3, align 4
  br label %16

13:                                               ; preds = %1
  %14 = load i32, i32* %2, align 4
  %15 = call i32 @memory_CalculateRealBlockSize(i32 noundef %14)
  store i32 %15, i32* %3, align 4
  br label %16

16:                                               ; preds = %13, %6
  %17 = load i32, i32* %3, align 4
  ret i32 %17
}

; Function Attrs: nounwind
declare dso_local void @free(i8* noundef) #2

; Function Attrs: noinline nounwind uwtable
define internal i32 @memory_CalculateRealBlockSize(i32 noundef %0) #0 {
  %2 = alloca i32, align 4
  %3 = alloca i32, align 4
  store i32 %0, i32* %2, align 4
  %4 = load i32, i32* %2, align 4
  store i32 %4, i32* %3, align 4
  %5 = load i32, i32* %3, align 4
  %6 = urem i32 %5, 1
  %7 = icmp ne i32 %6, 0
  br i1 %7, label %8, label %14

8:                                                ; preds = %1
  %9 = load i32, i32* %3, align 4
  %10 = urem i32 %9, 1
  %11 = sub i32 1, %10
  %12 = load i32, i32* %3, align 4
  %13 = add i32 %12, %11
  store i32 %13, i32* %3, align 4
  br label %14

14:                                               ; preds = %8, %1
  %15 = load i32, i32* %3, align 4
  %16 = load i32, i32* @memory_ALIGN, align 4
  %17 = urem i32 %15, %16
  %18 = icmp ne i32 %17, 0
  br i1 %18, label %19, label %27

19:                                               ; preds = %14
  %20 = load i32, i32* @memory_ALIGN, align 4
  %21 = load i32, i32* %3, align 4
  %22 = load i32, i32* @memory_ALIGN, align 4
  %23 = urem i32 %21, %22
  %24 = sub i32 %20, %23
  %25 = load i32, i32* %3, align 4
  %26 = add i32 %25, %24
  store i32 %26, i32* %3, align 4
  br label %27

27:                                               ; preds = %19, %14
  %28 = load i32, i32* %3, align 4
  ret i32 %28
}

declare dso_local i8* @memory_Malloc(i32 noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal void @flag_CheckFlagIdInRange(i32 noundef %0) #0 {
  %2 = alloca i32, align 4
  store i32 %0, i32* %2, align 4
  ret void
}

; Function Attrs: nounwind readonly willreturn
declare dso_local i64 @strlen(i8* noundef) #3

; Function Attrs: nounwind
declare dso_local i32 @sprintf(i8* noundef, i8* noundef, ...) #2

declare dso_local %struct._IO_FILE* @misc_OpenFile(i8* noundef, i8* noundef) #1

declare dso_local i32 @fputs(i8* noundef, %struct._IO_FILE* noundef) #1

declare dso_local void @fol_FPrintDFGSignature(%struct._IO_FILE* noundef) #1

; Function Attrs: noinline nounwind uwtable
define internal i32 @clause_IsFromInput(%struct.CLAUSE_HELP* noundef %0) #0 {
  %2 = alloca %struct.CLAUSE_HELP*, align 8
  store %struct.CLAUSE_HELP* %0, %struct.CLAUSE_HELP** %2, align 8
  %3 = load %struct.CLAUSE_HELP*, %struct.CLAUSE_HELP** %2, align 8
  %4 = getelementptr inbounds %struct.CLAUSE_HELP, %struct.CLAUSE_HELP* %3, i32 0, i32 14
  %5 = load i32, i32* %4, align 4
  %6 = icmp eq i32 %5, 16
  %7 = zext i1 %6 to i32
  ret i32 %7
}

declare dso_local %struct.LIST_HELP* @list_NReverse(%struct.LIST_HELP* noundef) #1

declare dso_local void @clause_FPrintCnfDFG(%struct._IO_FILE* noundef, i32 noundef, %struct.LIST_HELP* noundef, %struct.LIST_HELP* noundef, i32* noundef, i32* noundef) #1

declare dso_local void @clause_FPrintDFGStep(%struct._IO_FILE* noundef, %struct.CLAUSE_HELP* noundef, i32 noundef) #1

declare dso_local void @misc_CloseFile(%struct._IO_FILE* noundef, i8* noundef) #1

attributes #0 = { noinline nounwind uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #3 = { nounwind readonly willreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #4 = { nounwind readonly willreturn }
attributes #5 = { nounwind }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 14.0.6 (https://github.com/llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)"}
!4 = distinct !{!4, !5}
!5 = !{!"llvm.loop.mustprogress"}
!6 = distinct !{!6, !5}
!7 = distinct !{!7, !5}
!8 = distinct !{!8, !5}
!9 = distinct !{!9, !5}
!10 = distinct !{!10, !5}
!11 = distinct !{!11, !5}
!12 = distinct !{!12, !5}
!13 = distinct !{!13, !5}
