; ModuleID = '/project/test/llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/gglobals.c'
source_filename = "/project/test/llvm-test-suite/MultiSource/Benchmarks/Prolangs-C/TimberWolfMC/gglobals.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.clbox = type { i32, i32, i32, i32, i32, i32, i32, %struct.clbox* }
%struct.bellbox = type { i32, i32 }
%struct.wcbox = type { i32, i32, i32*, i32, %struct.wcbox* }
%struct.nodbox = type { %struct.flare*, %struct.flare*, i32 }
%struct.flare = type { i32, i32*, %struct.flare* }
%struct.tnode = type { i32, i32, %struct.tnode*, %struct.tnode*, %struct.tnode*, %struct.tnode*, %struct.tnode*, i32, i32, %struct.plist* }
%struct.plist = type { i32, %struct.plist* }
%struct.dlink2 = type { i32, %struct.dlink2*, %struct.dlink2* }
%struct.dlink1 = type { i32, %struct.dlink1*, %struct.dlink1* }
%struct.ebox = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, %struct.tnode* }
%struct.rect = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.edgebox = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct._IO_FILE = type { i32, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, %struct._IO_marker*, %struct._IO_FILE*, i32, i32, i64, i16, i8, [1 x i8], i8*, i64, %struct._IO_codecvt*, %struct._IO_wide_data*, %struct._IO_FILE*, i8*, i64, i32, [20 x i8] }
%struct._IO_marker = type opaque
%struct._IO_codecvt = type opaque
%struct._IO_wide_data = type opaque

@cellList = dso_local global %struct.clbox** null, align 8
@pitch = dso_local global i32 0, align 4
@xBellArray = dso_local global %struct.bellbox* null, align 8
@yBellArray = dso_local global %struct.bellbox* null, align 8
@eIndexArray = dso_local global i32** null, align 8
@xNodeArray = dso_local global %struct.wcbox** null, align 8
@yNodeArray = dso_local global %struct.wcbox** null, align 8
@xNodules = dso_local global %struct.nodbox* null, align 8
@yNodules = dso_local global %struct.nodbox* null, align 8
@numXnodes = dso_local global i32 0, align 4
@numYnodes = dso_local global i32 0, align 4
@numberCells = dso_local global i32 0, align 4
@edgeTransition = dso_local global i32 0, align 4
@cktName = dso_local global i8* null, align 8
@VDroot = dso_local global %struct.tnode* null, align 8
@HRroot = dso_local global %struct.tnode* null, align 8
@LEroot = dso_local global %struct.tnode* null, align 8
@BEroot = dso_local global %struct.tnode* null, align 8
@Vroot = dso_local global %struct.tnode* null, align 8
@Hroot = dso_local global %struct.tnode* null, align 8
@vChanEndRoot = dso_local global %struct.tnode* null, align 8
@vChanBeginRoot = dso_local global %struct.tnode* null, align 8
@hChanEndRoot = dso_local global %struct.tnode* null, align 8
@hChanBeginRoot = dso_local global %struct.tnode* null, align 8
@LEptrs = dso_local global %struct.dlink2** null, align 8
@BEptrs = dso_local global %struct.dlink2** null, align 8
@VDptrs = dso_local global %struct.dlink1** null, align 8
@HRptrs = dso_local global %struct.dlink1** null, align 8
@Vptrs = dso_local global %struct.dlink1** null, align 8
@Hptrs = dso_local global %struct.dlink1** null, align 8
@eArray = dso_local global %struct.ebox* null, align 8
@eNum = dso_local global i32 0, align 4
@rectArray = dso_local global %struct.rect* null, align 8
@numRects = dso_local global i32 0, align 4
@Hlist = dso_local global %struct.dlink1* null, align 8
@Vlist = dso_local global %struct.dlink1* null, align 8
@HRlist = dso_local global %struct.dlink2* null, align 8
@VRlist = dso_local global %struct.dlink2* null, align 8
@Hend = dso_local global %struct.dlink1* null, align 8
@Vend = dso_local global %struct.dlink1* null, align 8
@hFixedList = dso_local global %struct.dlink1* null, align 8
@vFixedList = dso_local global %struct.dlink1* null, align 8
@hFixedEnd = dso_local global %struct.dlink1* null, align 8
@vFixedEnd = dso_local global %struct.dlink1* null, align 8
@edgeList = dso_local global %struct.edgebox* null, align 8
@edgeCount = dso_local global i32 0, align 4
@numProbes = dso_local global i32 0, align 4
@hFixedEdgeRoot = dso_local global %struct.tnode* null, align 8
@vFixedEdgeRoot = dso_local global %struct.tnode* null, align 8
@hEdgeRoot = dso_local global %struct.tnode* null, align 8
@vEdgeRoot = dso_local global %struct.tnode* null, align 8
@hRectRoot = dso_local global %struct.tnode* null, align 8
@vRectRoot = dso_local global %struct.tnode* null, align 8
@bbl = dso_local global i32 0, align 4
@bbr = dso_local global i32 0, align 4
@bbb = dso_local global i32 0, align 4
@bbt = dso_local global i32 0, align 4
@fpdebug = dso_local global %struct._IO_FILE* null, align 8

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 14.0.6 (https://github.com/llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)"}
